# Generated by Django 5.2.1 on 2025-10-16 23:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumnos', '0003_remove_alumno_apoderados_and_more'),
        ('escuela', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PRESENTE', 'Presente'), ('AUSENTE', 'Ausente'), ('RETIRADO', 'Retirado'), ('JUSTIFICADO', 'Justificado')], max_length=20)),
                ('hora_registro', models.DateTimeField(auto_now=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados', to='alumnos.alumno')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados', to='escuela.curso')),
                ('usuario_registro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estados_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estado de Alumno',
                'verbose_name_plural': 'Estados de Alumnos',
                'db_table': 'estado_alumno',
                'unique_together': {('alumno', 'curso', 'fecha')},
            },
        ),
    ]
