# Generated by Django 5.2.1 on 2025-10-16 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadoalumno',
            name='fecha',
            field=models.DateField(),
        ),
    ]
