# Generated by Django 5.2.1 on 2025-10-18 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0003_remove_alumno_apoderados_and_more'),
        ('escuela', '0001_initial'),
        ('estados', '0002_alter_estadoalumno_fecha'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadoalumno',
            name='estado',
            field=models.CharField(choices=[('PRESENTE', 'Presente'), ('AUSENTE', 'Ausente'), ('RETIRADO', 'Retirado'), ('JUSTIFICADO', 'Justificado'), ('EXTENSION', 'Extensión')], max_length=20),
        ),
        migrations.CreateModel(
            name='HistorialEstadoAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(max_length=20)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('hora_cambio', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.alumno')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escuela.curso')),
                ('estado_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiales', to='estados.estadoalumno')),
                ('usuario_registro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Estado de Alumno',
                'verbose_name_plural': 'Historiales de Estados de Alumnos',
                'db_table': 'historial_estado_alumno',
                'ordering': ['-hora_cambio'],
            },
        ),
    ]
