# Generated by Django 5.2.1 on 2025-10-25 13:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0003_remove_alumno_apoderados_and_more'),
        ('escuela', '0001_initial'),
        ('estados', '0003_alter_estadoalumno_estado_historialestadoalumno'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadoalumno',
            name='estado',
            field=models.CharField(choices=[('AUSENTE', 'Ausente'), ('RETIRADO', 'Retirado'), ('EXTENSION', 'Extensión')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='historialestadoalumno',
            constraint=models.UniqueConstraint(fields=('alumno', 'fecha', 'estado'), name='unique_estado_por_dia_y_alumno'),
        ),
    ]
