# Generated by Django 5.2.1 on 2025-10-30 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estados', '0004_alter_estadoalumno_estado_and_more'),
        ('personas', '0005_alter_documentoidentidad_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadoalumno',
            name='retirado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retiros_realizados', to='personas.persona'),
        ),
        migrations.AddField(
            model_name='historialestadoalumno',
            name='retirado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_retiros', to='personas.persona'),
        ),
    ]
