# Generated by Django 5.2.1 on 2025-11-06 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estados', '0005_estadoalumno_retirado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadoalumno',
            name='foto_documento',
            field=models.ImageField(blank=True, help_text='Foto de respaldo del retiro (solo si no está en la base de datos)', null=True, upload_to='retiros_fotos/'),
        ),
    ]
