# Generated by Django 5.2.1 on 2025-11-06 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estados', '0006_estadoalumno_foto_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadoalumno',
            name='foto_documento',
            field=models.TextField(blank=True, help_text='Imagen en formato Base64 (data:image/jpeg;base64,...)', null=True),
        ),
    ]
