# Generated by Django 5.2.1 on 2025-11-07 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estados', '0007_alter_estadoalumno_foto_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadoalumno',
            name='retiro_anticipado',
            field=models.BooleanField(default=False, help_text='Indica si el retiro ocurrió antes del horario de término del curso.'),
        ),
    ]
