# Generated by Django 5.2.1 on 2025-10-24 02:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditoria',
            options={'ordering': ['-fecha']},
        ),
        migrations.AddField(
            model_name='auditoria',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
