# Generated by Django 5.2.1 on 2025-09-06 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ubicacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntidadAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('rut', models.CharField(blank=True, max_length=12, null=True)),
                ('representante', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'entidad_admin',
            },
        ),
        migrations.CreateModel(
            name='Establecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.CharField(blank=True, max_length=250, null=True)),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ubicacion.comuna')),
                ('entidad_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='establecimientos.entidadadmin')),
            ],
            options={
                'db_table': 'establecimiento',
            },
        ),
    ]
