# Generated by Django 5.2.1 on 2025-11-07 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='hora_inicio',
            field=models.TimeField(default='08:00', help_text='Hora de inicio de la jornada escolar para este curso'),
        ),
        migrations.AddField(
            model_name='curso',
            name='hora_termino',
            field=models.TimeField(default='15:00', help_text='Hora de término de la jornada escolar para este curso'),
        ),
    ]
