# Generated by Django 5.2.1 on 2025-09-24 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('apoderado', 'Apoderado'), ('profesor', 'Profesor'), ('porteria', 'Portería')], default='apoderado', max_length=20),
        ),
    ]
