# Generated by Django 5.2.1 on 2025-09-07 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usuario_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('apoderado', 'Apoderado'), ('profesor', 'Profesor'), ('alumno', 'Alumno')], default='alumno', max_length=20),
        ),
    ]
