# Generated by Django 5.2.1 on 2025-11-07 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('apoderado', 'Apoderado'), ('profesor', 'Profesor'), ('porteria', 'Portería'), ('furgon', 'Furgon')], default='apoderado', max_length=20),
        ),
    ]
