# Generated by Django 5.2.1 on 2025-09-06 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('codigo_iso_alpha_2', models.CharField(blank=True, max_length=2, null=True, unique=True)),
                ('codigo_iso_alpha_3', models.CharField(blank=True, max_length=3, null=True, unique=True)),
                ('codigo_iso', models.IntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'db_table': 'pais',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='regiones', to='ubicacion.pais')),
            ],
            options={
                'db_table': 'region',
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='comunas', to='ubicacion.region')),
            ],
            options={
                'db_table': 'comuna',
            },
        ),
    ]
