# Generated by Django 5.2.1 on 2025-11-18 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubicacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=20)),
                ('depto', models.CharField(blank=True, max_length=20, null=True)),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='direcciones', to='ubicacion.comuna')),
            ],
            options={
                'db_table': 'direccion',
            },
        ),
    ]
