# Generated by Django 5.2.1 on 2025-09-06 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escuela', '0001_initial'),
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apoderado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alumnos_como_apoderado', to='personas.persona')),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alumnos', to='escuela.curso')),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alumno', to='personas.persona')),
            ],
            options={
                'db_table': 'alumno',
            },
        ),
        migrations.CreateModel(
            name='PersonaAutorizadaAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_relacion', models.CharField(max_length=80)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personas_autorizadas', to='alumnos.alumno')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autorizaciones', to='personas.persona')),
            ],
            options={
                'db_table': 'persona_autorizada_alumno',
                'unique_together': {('alumno', 'persona')},
            },
        ),
        migrations.CreateModel(
            name='QrAutorizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_autorizacion', models.DateTimeField()),
                ('codigo_qr', models.CharField(max_length=120, unique=True)),
                ('valido_hasta', models.DateTimeField()),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qrs', to='alumnos.alumno')),
                ('persona_autorizada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qrs', to='alumnos.personaautorizadaalumno')),
            ],
            options={
                'db_table': 'qr_autorizacion',
                'unique_together': {('persona_autorizada', 'alumno', 'codigo_qr')},
            },
        ),
    ]
