# Generated by Django 5.2.1 on 2025-10-04 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
        ('personas', '0002_alter_persona_unique_together_alter_persona_run_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='apoderado',
        ),
        migrations.CreateModel(
            name='ApoderadoAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_relacion', models.CharField(max_length=80)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relaciones_apoderados', to='alumnos.alumno')),
                ('apoderado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relaciones_alumnos', to='personas.persona')),
            ],
            options={
                'db_table': 'apoderado_alumno',
                'unique_together': {('alumno', 'apoderado')},
            },
        ),
        migrations.AddField(
            model_name='alumno',
            name='apoderados',
            field=models.ManyToManyField(related_name='alumnos_asociados', through='alumnos.ApoderadoAlumno', to='personas.persona'),
        ),
    ]
