# Generated by Django 5.2.1 on 2025-10-06 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_remove_alumno_apoderado_apoderadoalumno_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='apoderados',
        ),
        migrations.AddField(
            model_name='personaautorizadaalumno',
            name='autorizado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='personaautorizadaalumno',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relaciones_personas', to='alumnos.alumno'),
        ),
        migrations.DeleteModel(
            name='ApoderadoAlumno',
        ),
    ]
