# Generated by Django 5.2.1 on 2025-11-13 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0003_remove_alumno_apoderados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaautorizadaalumno',
            name='parentesco',
            field=models.CharField(choices=[('Padre', 'Padre'), ('Madre', 'Madre'), ('Abuelo', 'Abuelo'), ('Abuela', 'Abuela'), ('Tío', 'Tío'), ('Tía', 'Tía'), ('Hermano', 'Hermano'), ('Hermana', 'Hermana'), ('Apoderado', 'Apoderado'), ('Otro', 'Otro')], default='Apoderado', max_length=20),
        ),
        migrations.AlterField(
            model_name='personaautorizadaalumno',
            name='tipo_relacion',
            field=models.CharField(default='apoderado', max_length=80),
        ),
        migrations.DeleteModel(
            name='QrAutorizacion',
        ),
    ]
