# Generated by Django 5.2.1 on 2025-11-24 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0004_personaautorizadaalumno_parentesco_and_more'),
        ('transporte', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='furgon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alumnos', to='transporte.furgon'),
        ),
    ]
