# Generated by Django 5.2.1 on 2025-09-06 02:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ubicacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=120)),
                ('apellido_uno', models.CharField(max_length=120)),
                ('apellido_dos', models.CharField(blank=True, max_length=120, null=True)),
                ('run', models.CharField(blank=True, max_length=10, null=True)),
                ('dv', models.CharField(blank=True, max_length=1, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('fono', models.CharField(blank=True, max_length=20, null=True)),
                ('comuna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='personas', to='ubicacion.comuna')),
                ('pais_nacionalidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='nacionales', to='ubicacion.pais')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='persona', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'persona',
                'unique_together': {('run', 'dv')},
            },
        ),
        migrations.CreateModel(
            name='DocumentoIdentidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=40)),
                ('identificador', models.CharField(max_length=64)),
                ('pais_emisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='documentos_emitidos', to='ubicacion.pais')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='documentos', to='personas.persona')),
            ],
            options={
                'db_table': 'documento_identidad',
                'unique_together': {('persona', 'tipo', 'identificador')},
            },
        ),
    ]
