# Generated by Django 5.2.1 on 2025-10-03 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='persona',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='persona',
            name='run',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.RemoveField(
            model_name='persona',
            name='dv',
        ),
    ]
