# Generated by Django 5.2.1 on 2025-10-18 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0003_alter_documentoidentidad_pais_emisor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='run',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
