# Generated by Django 5.2.1 on 2025-10-30 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0004_alter_persona_run'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentoidentidad',
            options={'verbose_name': 'Documento de Identidad', 'verbose_name_plural': 'Documentos de Identidad'},
        ),
        migrations.AlterModelOptions(
            name='persona',
            options={'verbose_name': 'Persona', 'verbose_name_plural': 'Personas'},
        ),
        migrations.AddField(
            model_name='persona',
            name='email',
            field=models.EmailField(blank=True, max_length=120, null=True),
        ),
    ]
