# Generated by Django 5.2.1 on 2025-11-15 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0005_alter_documentoidentidad_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
