# Generated by Django 5.2.1 on 2025-11-18 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0006_persona_direccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='direccion',
        ),
    ]
