# Generated by Django 5.2.1 on 2025-11-18 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0007_remove_persona_direccion'),
        ('ubicacion', '0002_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='direccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personas', to='ubicacion.direccion'),
        ),
    ]
