# Generated by Django 5.2.1 on 2025-11-18 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0008_persona_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, null=True),
        ),
    ]
